import Head from 'next/head'
import type { AppProps } from 'next/app'
import { Wrapper } from '@/store/Store'
import '@/styles/globals.css'
import '@/styles/login.css'
import '@/styles/home.css'

function App({ Component, pageProps }: AppProps) {
	return (
		<>
			<Head>
				<title>Spoti Bolivar</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.svg' />
			</Head>
			<Component {...pageProps} />
		</>
	)
}

export default Wrapper.withRedux(App)
